@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.hamncheese.client.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;