modLoader="javafml"
loaderVersion="[40,)"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
issueTrackerURL="https://github.com/CoffeeCatRailway/HamNCheese/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
logoFile = "icon.png"
updateJSONURL = "https://raw.githubusercontent.com/CoffeeCatRailway/Online-Mod-Resources/main/Ham%20N'%20Cheese/update_checker.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hamncheese"
authors = "CoffeeCatRailway"
credits = "Nyctoniac for mouse model & any/all others who've helped!"
description = '''
Adds in lots of ham and cheese related foods.

Disclaimer: I only upload to https://www.curseforge.com

Discord: https://discord.gg/GkeexxWnyz
'''

[modproperties.${id}]
catalogueItemIcon="${id}:block_of_cheese"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "pollen"
mandatory = true
versionRange = "[1,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${id}]]
modId = "jei"
mandatory = false
versionRange = "[9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "waila"
mandatory = false
versionRange = "[4.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "appleskin"
mandatory = false
versionRange = "[2.4,)"
ordering = "NONE"
side = "BOTH"