@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.hamncheese.common.entity.ai;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;