@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.hamncheese.common.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;