modLoader="javafml"
loaderVersion="[36,)"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
issueTrackerURL="https://github.com/CoffeeCatRailway/HamNCheese/issues"

[[mods]]
modId="hamncheese"
version="${version}"
displayName="${name}"
logoFile="logo.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/coffeecheese"
authors="${author}"
credits="ManWithoutTaste for mouse model"
description='''
Adds in lots of ham and cheese related foods.

Discord: https://discord.com/invite/JM4NjRzZPS
Credit to 'https://github.com/SystemZeeWorkshop/modding-template'
'''

[[dependencies.hamncheese]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.hamncheese]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17]"
ordering="NONE"
side="BOTH"
[[dependencies.hamncheese]]
modId="jei"
mandatory=false
versionRange="[7,]"
ordering="NONE"
side="CLIENT"
[[dependencies.hamncheese]]
modId="biomesoplenty"
mandatory=false
versionRange="[1.16.5-13,]"
ordering="AFTER"
side="BOTH"