@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.hamncheese.common.item;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;