@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package coffeecatrailway.hamncheese.common.inventory;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;